---
- hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: creating dummy inventory
      tower_role:
        team: "test-team"
        role: admin
        state: present
        #project: git-ansible
        inventory: dummy
